import ProjectCard, { ProjectCardProps } from "./project-card";

const PROJECT_DATA: ProjectCardProps[] = [
  {
    id: 1,
    title: "INTERA-ERP",
    category: "Business System",
    year: "2026",
    width: 1608,
    height: 1103,
    href: "https://erp.arihub.my.id/attendance",
    thumbnailSrc: "/assets/projects/interaerp/card.webp",
    gradient: "#014880",
    radial: "",
  },
  {
    id: 2,
    title: "Vida-Flo IV Hydration Multi-Location Website",
    category: "Healthcare & Wellness Platform",
    year: "2025",
    width: 1608,
    height: 1103,
    href: "https://govidaflo.com/",
    thumbnailSrc: "/assets/projects/vidaflo/card.webp",
    gradient: "#002759",
    radial: "",
  },
  {
    id: 3,
    title: "12 Days of Christmas Giveaway",
    category: "Event Campaign Website",
    year: "2025",
    width: 1608,
    height: 1103,
    href: "https://ppspl0d181-staging.wpdns.site/",
    thumbnailSrc: "/assets/projects/smalltowntnchristmas/card.webp",
    gradient: "#5f131d",
    radial: "",
  },
  {
    id: 4,
    title: "THP Roofing of Knoxville",
    category: "Local Business Website",
    year: "2025",
    width: 1608,
    height: 1103,
    href: "https://m4mdwy3str-staging.wpdns.site/",
    thumbnailSrc: "/assets/projects/thproofing/card.webp",
    gradient: "#005d7d",
    radial: "#014880",
  },
  {
    id: 5,
    title: "Taylor & Travis Animated Wedding Invitation",
    category: "Digital Wedding Invitation",
    year: "2026",
    width: 1608,
    height: 1103,
    href: "https://taylortravis.toondangan.com/",
    thumbnailSrc: "/assets/projects/taylor/card.mp4",
    gradient: "",
    radial: "",
  },
  {
    id: 6,
    title: "Toondangan",
    category: "Media Creative",
    year: "2026",
    width: 1608,
    height: 1103,
    href: "https://toondangan.com/",
    thumbnailSrc: "/assets/projects/toondangan/card.webp",
    gradient: "#7b3d10",
    radial: "",
  },
  {
    id: 7,
    title: "Visit Perth Amboy Tourism Website",
    category: "Tourism & Destination Website",
    year: "2025",
    width: 1608,
    height: 1103,
    href: "/projects/perthamboy",
    thumbnailSrc: "/assets/projects/perthamboy/card.webp",
    gradient: "#351d3f",
    radial: "#41348c",
  },
  {
    id: 8,
    title: "",
    category: "",
    year: "",
    width: 1608,
    height: 1103,
    href: "https://ai7gb1v2kj-staging.wpdns.site/",
    thumbnailSrc: "/assets/projects/maconcounty/card.webp",
    gradient: "#3D543A",
    radial: "#26371660",
  },
  {
    id: 9,
    title: "",
    category: "",
    year: "",
    width: 1608,
    height: 1103,
    href: "https://f82jo15o0k-staging.wpdns.site/",
    thumbnailSrc: "/assets/projects/decatur/card.webp",
    gradient: "#323323",
    radial: "#31331c",
  },
  {
    id: 10,
    title: "Dimensional Search Franchise",
    category: "Corporate Website",
    year: "2026",
    width: 1608,
    height: 1103,
    href: "https://dimensionalsearch.com/franchise/",
    thumbnailSrc: "/assets/projects/dimensional/card.webp",
    gradient: "#111a39",
    radial: "#45446d",
  },
];

export default function ProjectsSection() {
  return (
    <section className="flex w-full flex-col">
      <div className="grid w-full grid-cols-1 items-start gap-y-8 md:grid-cols-3 md:gap-x-3">
        {PROJECT_DATA.map((project, index) => (
          <ProjectCard key={project.id} {...project} priority={index === 0} />
        ))}
      </div>
    </section>
  );
}
